# The "init:" keyword, below, requires either version "2.2"
# or "2.3".
version: "2.3"

services:
  lms:
    image: nordewal/kodi-gbm
    devices:
      - "/dev/input:/dev/input"
      - "/dev/snd:/dev/snd"
      - "/dev/dri:/dev/dri"
    group_add:
      - video
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - kodi:/root/.kodi
      - /media:/media # my media store
    ports:
      - "8080:8080"
      - "8081:9090"
      - "9777:9777/udp"
    command: /usr/lib/kodi/kodi-gbm
    init: true

volumes:
  kodi:
